language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: eWsBlazhG86vi8pNNCvLEgoBNf+ObecEoUFlJqwb4J3D9mivLDlcuUvTBt4xUaUmjdNlONJabMg0QO7rJJtOsH6BOUev97cF6oEtRIZ8+qNymzUo9tm4FwMmlm2dfxcjKnDwJzs5RrSkgVgM+ZNKPMFy8ihiZDV9BzD1+yjkbkC4Fg5CIfsleEolGzDfCKp/btIRbhkOGEI23+FSvhLB+HrnlKYu+aZPSUIhfrHS3ND8cvvqwVJtrXc54RzApoyxvQ+9i1jXqBrXyeTAdD6tXdzdQqRlZXK2eWXJkzn/9pwC71LDjsUsdwPDun9wC5o749IyNE7BLM1mT9MFgAXUssEolQUWoYBqQnZ7E5R3nEWQzz+bP8eyHgp5AJeEjisAWFl7Er7m0NidhXVSWAiPUktL3IdDLJnXIwP8fmXa4mxWTb0vWPzjw/Oym9aNIIARA3w1Pdy01rX/XsK2Q3FKIPpMsn4erDZnG5uueqiZ26A1C8tw1MmCFlKNhPLK77ezyKQ6LldwQEsPM6ogKU/qIzWjWtlxsUhybISIm7HZLeQrxDNGSyW2GoqMMABtTnUFGDptAYI0ag1lJNquDXuRALtzj582r1wPINemkbEuA97SiEOLizczyDB8hoc5bHBAq6GrvfDCa9KXBePECMuZjhXVH4ivtw1VKwxdtq09QTo=
  app: blooming-thicket-55082
  on:
    repo: romklao/capstone_lego
